workflows:
  ios-build:
    name: iOS Unsigned Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: 3.19.6
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Set up Flutter configuration
        script: |
          flutter config --no-analytics
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS IPA (Unsigned)
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
